version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:

      - pwd
      - ls -lrt
      - npm install
      - npm install -g @angular/cli
      - npm update

      - ls -lrt

  pre_build:
    commands:
      - echo pre-Build started on `date`
      - echo "aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`

      - ng build --configuration=production
      - npm prune --production

      - aws s3 cp s3://studi-interspe/angular/prod/ssl/studi-public.crt .
      - aws s3 cp s3://studi-interspe/angular/prod/ssl/studi-private.key .
      - aws s3 cp s3://studi-interspe/angular/prod/ssl/studi-cacert.crt .
      - aws s3 cp s3://studi-interspe/angular/prod/ssl/httpd-ssl.conf .

      - echo "docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG ."
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .

      - echo "docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG"
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

      - echo "docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG"
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo post-Build started on `date`

      - cp appspec.yml dist/
      - cp -r scripts dist/

      - echo Build completed on `date`
artifacts:
  base-directory: dist
  files:
    - "**/*"
